title: "George's STAT 787 Showcase"
baseURL: "http://example.org/"
languageCode: "en-us"
theme: "blank"
author: "Chenliang Cao"

params:
  avatar: "avatar.jpg"

menu:
  main:
    - name: "Home"
      url: "/"