baseURL: "https://yourdomain.com/"
title: "My Classwork Showcase"
languageCode: "en-us"
theme: "blank" # if you are using a custom theme
paginate: 5 # the number of items per page for lists

# Configure permalinks
permalinks:
  introduction: /introduction/
  shiny-app: /shiny-app/
  rmarkdown-files: /rmarkdown-files/

# Configure menu
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Introduction"
      url: "/introduction/"
      weight: 2
    - name: "Shiny App"
      url: "/shiny-app/"
      weight: 3
    - name: "R Markdown Files"
      url: "/rmarkdown-files/"
      weight: 4
      
