baseURL: "http://chenlianggeorgecao.netlify.app/"
title: "My Classwork Showcase"
languageCode: "en-us"
theme: "blank" # if you are using a custom theme

# Configure menu
menu:
  main:
    - name: "Shiny App"
      url: "/Shinyapp.pdf"
      weight: 1
    - name: "Homework1"
      url: "/homework1.pdf"
      weight: 2
    - name: "Homework2"
      url: "/homework2.pdf"
      weight: 3
    - name: "Homework3"
      url: "/homework3.pdf"
      weight: 4

      
