baseURL: https://chengeorgeliangcao.netlify.app/
languageCode: en-us
theme: aafu
build:
  writeStats: yes
params:
  aboutme:
    description: I am a graduated student from RIT. I study Applied Statistics and I had a 
      master degree of Data Science from RIT as well. I am from Shanghai,China. This is my
      STAT-787 showcase.
    icon: fas fa-user
    title: About Me
  author: Darshan Baral
  description: Website title
  education:
    icon: fas fa-graduation-cap
    list:
      - college: University of Rochester
        dates: 2012 - 2017
        degree: B.S. in Applied Mathematic
      - college: Rochester Insititute of Technology
        dates: 2020 - 2022
        degree: M.S. in Data Science
        thesis_title: 'Anomaly Detection for Muultivariate Time-Series'
        thesis_url: '#'
      - college: Rochester Insititute of Technology
        dates: 2022 - Present
        degree: M.S. in Applied Statisitcs
    title: Education
  experience:
    icon: fas fa-briefcase
    list:
      - company: Shanghai Fire Technology Engineering Co,Ltd.
        dates: 2018 - 2020
        position: Project manager assistant
      - company: Shanghai Haitong Securities Co,Ltd
        dates: June.2015-Aug.2015
        position: Summer Interm
        url: 'https://www.htsec.com/ChannelHome/index.shtml'
    title: Experiences
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\r\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\r\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\r\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\r\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\r\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\r\n        "
    use: yes
  hobby:
    icon: fas fa-gamepad
    list:
      - hobby: Saxophone
      - hobby: Hiking
      - hobby: Lego
    title: Hobbies
  profile:
    location: Rochester, NY
    name: Chenliang, Cao.
    photo: profile.jpg
    tagline: George
  project:
    icon: fas fa-project-diagram
    list:
      - description: Description of the project
        title: Homework 1
        url: '/content/homework1'
      - description: Description of the project
        title: Homework 2
        url: '#'
      - description: Description of the project
        title: Homework 3
        url: '#'
      - description: Description of the project
        title: Shiny-App Project
        url: '#'
    title: Projects
  publication:
    format:
      - date
      - authors
      - title
      - journal
    icon: fas fa-book
    list:
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Journal Articles
        url: '#'
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Journal Articles
        url: '#'
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Proceedings
        url: '#'
    title: Publications
    types:
      - Journal Articles
      - Proceedings
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  skill:
    icon: fas fa-cogs
    list:
      - skill: Skill 1, Skill 2
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
    panelId: skill-panel
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: '#'
      - icon: fab fa-stack-overflow
        title: StackOverflow
        url: '#'
      - icon: fab fa-github
        title: GitHub
        url: '#'
      - icon: fab fa-twitter
        title: Twitter
        url: '#'
      - icon: fab fa-orcid
        title: Orcid
        url: '#'
      - icon: ai ai-google-scholar
        title: Google Scholar
        url: '#'
      - icon: fab fa-researchgate
        title: ResearchGate
        url: '#'
    title: Links
  theme:
    mainTheme: ocean
    showAttribute: yes
    singlePage: no
  title: Aafu theme
