baseURL: "http://chengeorgeliangcao.netlify.app/"
title: "My Classwork Showcase"
languageCode: "en-us"
theme: "blank" # if you are using a custom theme


# Configure permalinks
permalinks:
  shiny-app: /shiny-app/
  homework1: /homework1/
  homework2: /homework2/
  homework3: /homework3/

# Configure menu
menu:
  main:
    - name: "Shiny App"
      url: "/shiny-app/"
      weight: 1
    - name: "Homework1"
      url: "/homework1/"
      weight: 2
    - name: "Homework2"
      url: "/homework2/"
      weight: 3
    - name: "Homework3"
      url: "/homework3/"
      weight: 4
      
